### PR TITLE
Add passing modulation shaping to register.

### LINKED ISSUE #10: ModulationShaping bits not set in setDataModule function
The setDataModul function is not using modulationshaping parameter to set the ModulationShaping bits in the DATA_MODUL register:

```
void setDataModul(uint8_t processing, bool use_ook, uint8_t modulationshaping){
            this->writeRegister(RFM69_DATA_MODUL, (processing << 6) + (use_ook << 3));};
```

### PR DESCRIPTION
**Pull request by iwanders**
Reported in #10. Closes #10.

@jonsole, thanks for reporting this. I can't test this in hardware because I don't have access to it at the moment. Any chance you could check this works on actual hardware? I've just looked at the datasheet to make the correction, but ideally would like to have confirmation that it works on hardware as well before merging.

### CODE REVIEW

**Comment by jonsole** [comment]
At the moment I don't have a fully working setup.  I was using your library as a reference when writing my own C library and just noticed the missing field.

**Comment by jonsole** [comment]
BTW, I think the DataMode field of the same register is being set incorrectly  The function is shifting the field left by 6 bits, so it's settings bits 6 & 7 but the actual field is in bits 5 & 6.  It works for Packet Mode as it's value is 0b00.

**Comment by jonsole** [comment]
Below are 2 recordings of 153600 bps.  The first recording is with the change that applies RFM69_DATAMODUL_SHAPING_GFSK_BT_0_5 correctly, the second recording is without the shaping set.

modulation_difference

**Comment by jonsole** [comment]
Spectrogram with and without shaping set:

spectrum_difference

**Comment by iwanders** [comment]
> I think the DataMode field of the same register is being set incorrectly The function is shifting the field left by 6 bits, so it's settings bits 6 & 7 but the actual field is in bits 5 & 6. It works for Packet Mode as it's value is 0b00.

Glad someone is paying attention! Thanks for mentioning this second issue. I've pushed a commit to fix it.

> Below are 2 recordings of 153600 bps. The first recording is with the change that applies RFM69_DATAMODUL_SHAPING_GFSK_BT_0_5 correctly, the second recording is without the shaping set.

Very cool! I've never seen plots like this, are these captured with one of those RTL2832U radio dongles? Or with something fancier?

My knowledge of radio signals is fairly limited so when interpreting this I presume the lower noise in the top one shows the modulation shaping has a positive effect? And in the second image you posted the top image the signal has more contrast to the background (indicating better signal to noise ratio, so same as the first image)? Should I be able to see the actual shaping effect in the waveform as well, the first plot seems to have less jagged edges?

Please check the proposed improvements one last time. I'll merge the fix if you give it a :thumbsup:.

**Comment by jonsole** [comment]
Yes, they were captured with a RTL2832U dongle and Universal Radio Hacker software.  They're great for actually seeing what's going on over the air.

 Your interpretation of the images is correct, with the shaping turned on the transition between the 2 frequencies is filtered so the modulation is smoothed out which gives less jagged edges in the first plot of the first image and less RF splatter in the first plot of the second image.

I've doubled checked the changes, I believe they are correct and we have evidence that the changes effect the RF in the expected way.  So I think the fix can be merged. 👍.

**Comment by iwanders** [comment]
Merged. Thanks @jonsole for reporting this and verifying the fix. (And posting cool images! :D)

**Pull request merged**
